# /src/Aliznet/WCSBundle/Resources/config/doctrine/CategoryTranslation.orm.yml
Aliznet\WCSBundle\Entity\CategoryTranslation:
    type: entity
    table: Category_Translation
    fields:
        name:
            type: string
            length: 255
            nullable: true
        description:
            type: string
            length: 255
            nullable: true
        longDescription:
            type: string
            length: 255
            nullable: true
        keyword:
            type: string
            length: 255
            nullable: true
            
 

